[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"


[project]
name = "Karabo-Pipeline"


[project.optional-dependencies]
    dev = [
        "mypy == 0.991",
        "mypy-extensions == 0.4.3",
		"flake8 == 6.0.0",
		"isort == 5.11.4",
		"black == 22.12.0",
		"pydocstyle == 6.3.0",
        "pytest == 7.2.0",
        "pre-commit == 2.21.0"
    ]