{% set name = "Karabo-Pipeline" %}

package:
  name: {{ name|lower }}
  version: {{ KARABO_VERSION }}

source:
  path: ../

build:
  string: {{ CHANNEL_LABEL }}

requirements:
  build:
    - python=3.9
    - pip
  host:
    - python=3.9
    - pip
  run:
    - python=3.9
    - numpy<=1.22
    - matplotlib
    - oskarpy
    - rascil
    - astropy
    - requests
    - healpy
    - pinocchio # [linux]
    - katbeam
    - tools21cm
    - eidos
    - libcufft
    - cuda-cudart
    - ska-gridder-nifty-cuda=0.0.11 # Depends on cuda-toolkit


test:
  imports:
    - karabo

about:
  home: https://github.com/i4Ds/Karabo-Pipeline
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Astronomy data centric pipeline built for SKA (Square Kilometer Array) and beyond.'
  description: |
   Astronomy data centric pipeline built for SKA (Square Kilometer Array) and beyond.
  doc_url: https://github.com/i4Ds/Karabo-Pipeline/wiki
  dev_url: https://github.com/i4Ds/Karabo-Pipeline

extra:
  recipe-maintainers:
    - lukas.gehrig@fhnw.ch
