name: Build Docs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Create Environment
        shell: bash -l {0}
        run: |
          conda env create -f environment-dev.yaml
          conda activate karabo_dev_env
          conda install -c conda-forge -y --file doc/doc_packages.txt
      - name: Build Docs
        shell: bash -l {0}
        run: |
          conda activate karabo_dev_env
          sphinx-apidoc . -o doc/_build
          make html
      - name: Archive doc build
        uses: actions/upload-artifact@v3
        with:
          name: docs_built
          path: build/
      - name: Commit built-doc
        run: |
          git config --global user.name 'PaperBot'
          git config --global user.email 'actions@github.com'
          git fetch origin
          
          echo "delete old branch and create a new one"
          git push origin -d pages_source || true
          git checkout -b pages_source

          echo "add new files"
          touch .nojekyll
          git add .
          git commit -m "updated docs"
          git push -u origin pages_source
