name: Conda Build

on:
  release:
    types: [published]
  workflow_dispatch:


jobs:
  conda-build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Get Previous tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - name: Set variables, Build Karabo
        shell: bash -l {0}
        run: |
          KARABO_TAG=${{ steps.get-latest-tag.outputs.tag }}
          export KARABO_VERSION="${KARABO_TAG:1}"
          echo "__version__ = \"${KARABO_VERSION}\"" > karabo/version.py
          conda install conda-build
          conda build -c i4ds/label/main -c i4ds -c conda-forge .
      - name: Publish to Conda
        shell: bash -l {0}
        run: |
          conda activate base
          conda install anaconda-client
          anaconda -t ${{ secrets.ANACONDA_SECRET }} upload /opt/conda/conda-bld/linux-64/karabo-pipeline-*.tar.bz2 --force
  
