name: Conda Build

on:
  release:

  workflow_dispatch:

jobs:
  conda-build:
    runs-on: ubuntu-20.04

    steps:
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Install conda build
        run: |
          conda install conda-build anaconda
          conda config --append channels conda-forge
          conda config --append channels i4ds
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Conda
        run: |
          cd conda
          conda build .
      - name: Publish to Conda
        shell: bash -l {0}
        run: |
          conda activate base
          anaconda -t ${{ secrets.ANACONDA_SECRET }} upload /usr/share/miniconda/conda-bld/noarch/karabo-pipeline-*.tar.bz2 --force
