name: Conda Build

on:
  release:
    types: [published]
  workflow_dispatch:


jobs:
  conda-build:
    runs-on: ubuntu-latest
    container: ghcr.io/i4ds/mambabuild-docker:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get Previous tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - name: Install conda build
        shell: bash -l {0}
        id: channels
        run: |
          KARABO_TAG=${{ steps.get-latest-tag.outputs.tag }}
          export CHANNEL_LABEL=rel_$(echo $KARABO_TAG | cut -d '.' -f 1-2)
          echo "label=$CHANNEL_LABEL" >> $GITHUB_OUTPUT
          conda config --append channels "i4ds/label/$CHANNEL_LABEL"
          conda config --append channels nvidia/label/cuda-11.7.0
          conda config --append channels conda-forge
      - name: Build Conda
        run: |
          cd conda
          KARABO_TAG=${{ steps.get-latest-tag.outputs.tag }}
          export KARABO_VERSION="${KARABO_TAG:1}"
          export CHANNEL_LABEL={{ steps.channels.outputs.label }}
          conda mambabuild .
      - name: Publish to Conda
        shell: bash -l {0}
        run: |
          conda activate base
          anaconda -t ${{ secrets.ANACONDA_SECRET }} upload /opt/conda/conda-bld/noarch/karabo-pipeline-*.tar.bz2 --label {{ steps.channels.outputs.label }} --force
