name: Dev Workflow

on:
  workflow_run:
    workflows: ["Conda Build"]
    types:
      - completed

  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Aussumes that current repo-tag matches karabo:latest on anaconda.org
      - name: Get Previous tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: docker/Dockerfile.user
          context: .
          push: true
          tags: i4ds/karabo-pipeline:${{ steps.get-latest-tag.outputs.tag }}, i4ds/karabo-pipeline:latest