# This is a template workflow that exists at the default branch for testing purpose at another branch.
# DO NOT CHANGE THIS WORKFLOW when you merge your branch to the default branch!
name: Dev Workflow

# on:
#   workflow_dispatch:

# jobs:
#   job-name:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3


# name: Purge Image

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        required: true
        type: string
      IMAGE_TAG:
        required: true
        type: string

jobs:
  Purge_Dev_Image:
    uses: bots-house/ghcr-delete-image-action@v1.1.0
    with:
      owner: ${{ github.repository_owner }}
      name: ${{ inputs.IMAGE_NAME }}
      token: ${{ secrets.GITHUB_TOKEN }}
      tag: ${{ inputs.IMAGE_TAG }}