name: Create Nightly Build

env:
  NIGHTLY_BUILD: True
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  schedule: # Every night at 3am
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  conda-build:
    runs-on: ubuntu-20.04
    container: ghcr.io/i4ds/mambabuild-docker:latest

    steps:
      - name: Print Out Environment
        run: |
          echo "NIGHTLY_BUILD: $NIGHTLY_BUILD"
          echo "REGISTRY: $REGISTRY"
          echo "IMAGE_NAME: $IMAGE_NAME"
      - name: Install conda build
        run: |
          conda config --append channels conda-forge
          conda config --append channels i4ds
          conda config --append channels nvidia/label/cuda-11.7.0
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Conda
        run: |
          cd conda
          conda mambabuild .
      - name: Publish to Conda
        shell: bash -l {0}
        run: |
          conda activate base
          anaconda -t ${{ secrets.ANACONDA_SECRET }} upload /opt/conda/conda-bld/noarch/karabo-pipeline-*.tar.bz2 --label nightly --force
