name: Purge Image

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        required: true
        type: string
      IMAGE_TAG:
        required: true
        type: string

jobs:
  Purge_Image:
    runs-on: ubuntu-latest
    steps:
      - name: Purge image
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: ${{ github.repository_owner }}
          name: ${{ inputs.IMAGE_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ inputs.IMAGE_TAG }}
