name: Test Software

on: [ push ]

jobs:
  TestKarabo:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          conda create -n test_env python=3.7
          conda install --file requirements.txt
      - name: Test Code
        run: | 
          python -m unittest test