name: Test Software

on: [ push ]

jobs:
  TestKarabo:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          ls
          conda env create -f environment.yaml
      - name: Test Code
        shell: bash -l {0}
        run: | 
          conda activate karabo_env
          python -m unittest test