name: Tests

on: [ push ]

jobs:
  Build_Dev_Image:
    uses: ./.github/workflows/build-dev-docker-image.yaml
    with:
      REGISTRY: ghcr.io
      IMAGE_NAME: karabo-pipeline-dev


  Test_Formatting:
    needs: [ Build_Dev_Image ]
    runs-on: ubuntu-latest
    container: ghcr.io/i4ds/karabo-pipeline:${{ needs.Build_Dev_Image.outputs.imagetag }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install formatting-tools
        run: pip install -r requirements.txt
      - name: Check-flake8
        run: flake8 .
      - name: check-black
        run: black --check .
      - name: check-isort
        run: isort --check .

  Test_Karabo:
    needs: [ Test_Formatting, Build_Dev_Image ]
    runs-on: ubuntu-latest
    container: ghcr.io/i4ds/karabo-pipeline:${{ needs.Build_Dev_Image.outputs.imagetag }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Test Code
        shell: bash -l {0}
        run: |
          export IS_GITHUB_RUNNER=true
          export RUN_SLOW_TESTS=false
          python -m xmlrunner -o ./test-reports/junit
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-reports/**/*.xml

  Purge_Dev_Image:
    if: always()
    needs: [ Build_Dev_Image, Test_Formatting, Test_Karabo ]
    uses: ./.github/workflows/purge-dev-image.yaml
    with:
      IMAGE_NAME: karabo-pipeline-dev
      IMAGE_TAG: ${{ needs.Build_Dev_Image.outputs.imagetag }}
