name: Test Nightly Build

on:
  workflow_run:
    workflows: ["Create Nightly Build"]
    types:
      - completed
  workflow_dispatch:


jobs:
  Test_Nightly_Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-22.04"]
        python-version: ["3.9"]
    steps:
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge, i4ds, nvidia/label/cuda-11.7.0
          python-version: ${{ matrix.python-version }}
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Create Environment
        run: |
          mamba init
          mamba create -n test_karabo python=${{ matrix.python-version }}
      - name: Install Karabo
        run: |
          mamba init
          mamba activate test_karabo
          mamba install -c "i4ds/label/nightly" karabo-pipeline --yes
      - name: Test Nightly Build
        run: |
          mamba init
          mamba activate test_karabo
          python -c "from karabo.util.testing import run_tests; run_tests()"