name: Test Nightly Build

on:
  workflow_run:
    workflows: ["Create Nightly Build"]
    types:
      - completed
  workflow_dispatch:

jobs:
  Test_Nightly_Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04"]
        python-version: ["3.9"]
    steps:
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          use-mamba: true
          python-version: ${{ matrix.python-version }}
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Create Environment
        shell: bash -l {0}
        run: |
          mamba create -n test_karabo python=${{ matrix.python-version }}
          mamba activate test_karabo
      - name: Install Karabo
        run: |
          mamba config --append channels conda-forge
          mamba config --append channels i4ds
          mamba config --append channels nvidia/label/cuda-11.7.0
          mamba install -c "i4ds/label/nightly" karabo-pipeline --yes
      - name: Test Nightly Build
        run: |
          mamba activate test_karabo
          python -c "from karabo.util.testing import run_tests; run_tests()"