name: Tests

on: [ push ]

jobs:
  BUILD_DEV_IMAGE:
    runs-on: ubuntu-latest
    steps:
      - name: Call "Build Dev Image" workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: Dev Workflow

  TEST_FORMATTING:
    runs-on: ubuntu-latest
    container: ghcr.io/i4ds/karabo-pipeline:dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install formatting-tools
        run: pip install -r requirements.txt
      - name: Check-flake8
        run: flake8 .
      - name: check-black
        run: black --check .
      - name: check-isort
        run: isort --check .

      
  Test_Karabo:
    needs: TEST_FORMATTING
    runs-on: ubuntu-latest
    container: ghcr.io/i4ds/karabo-pipeline:dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Test Code
        shell: bash -l {0}
        run: |
          conda activate karabo_dev_env
          export IS_GITHUB_RUNNER=true
          export RUN_SLOW_TESTS=false
          python -m xmlrunner -o ./test-reports/junit
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-reports/**/*.xml
