name: Test Nightly Build

on:
  workflow_run:
    workflows: ["Create Nightly Build"]
    types:
      - completed
  workflow_dispatch:

jobs:
  Test_Nightly_Build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Create Environment
        shell: bash -l {0}
        run: |
          conda create -n test_karabo python=3.9.13
          conda activate test_karabo
          conda install -c conda-forge __glibc=2.33 --yes
      - name: Install Karabo
        run: |
          conda install -c "i4ds/label/nightly" karabo-pipeline --yes
      - name: Test Nightly Build
        run: |
          conda activate test_karabo
          python -c "import karabo; karabo.util.testing.run_tests()"