name: Tests

on: [ push ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Build_Dev_Image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      tag: ${{ steps.imagetag.outputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete untagged images
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: ${{ github.repository_owner }}
          name: ${{ github.event.repository.name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          untagged-keep-latest: 3

      - name: Create image tag
        id: imagetag
        shell: bash -l {0}
        run: |
          UUID=$(uuidgen)
          IMAGE_TAG=dev-"${UUID:0:8}"
          echo "tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw, value=${{ steps.imagetag.outputs.tag }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: docker/Dockerfile.dev
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  Test_Formatting:
    needs: Build_Dev_Image
    runs-on: ubuntu-latest
    container: ghcr.io/i4ds/karabo-pipeline@${{ needs.Build_Dev_Image.outputs.tag }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install formatting-tools
        run: pip install -r requirements.txt
      - name: Check-flake8
        run: flake8 .
      - name: check-black
        run: black --check .
      - name: check-isort
        run: isort --check .

  Test_Karabo:
    needs: Test_Formatting
    runs-on: ubuntu-latest
    container: ghcr.io/i4ds/karabo-pipeline@${{ needs.Build_Dev_Image.outputs.tag }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Test Code
        shell: bash -l {0}
        run: |
          export IS_GITHUB_RUNNER=true
          export RUN_SLOW_TESTS=false
          python -m xmlrunner -o ./test-reports/junit
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-reports/**/*.xml

  Purge_Image:
    if: always()
    needs: [Build_Dev_Image, Test_Formatting, Test_Karabo]
    runs-on: ubuntu-latest
    steps:
      - name: Delete image
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: ${{ github.repository_owner }}
          name: ${{ github.event.repository.name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.Build_Dev_Image.outputs.tag }}
